#!/usr/bin/env bash

# $HOME/bin/login/DCL-magik
# Lorin Ricker: personal DCL aliases

# Implementing a set of emulated DCL (OpenVMS) commands in a Linux/bash
# environment requires a rather elaborate set of tricks, especially in
# order to defeat aggressive bash/shell globbing of wildcard arguments.
#
# See "$dlb/Linux/HowTos/HowTo - Turn Off Bash Globbing for Application.txt"
# for background experiments and implementation.
#
# See also "$tpg/MEP/3 - A Ruby DCL-Emulator (2015)/*.{doc,pdf}".
#
# See also $rby/dcl.rb and $rby/lib/DCLcommand.rb for full implementation,
# including the use of sym-links in $bin/dcllinks/ for command dispatch.
#

shF="$( basename ${0#-} ) - DCL-magik"
Ident="${shF}  # (LMR version 2.01 of 07/21/2016)"
[ "$DEBUGMODE" = "1" ] && echo "%login-I, ${Ident}"

# $ sudo mkdir /mnt/class8 -v
# [sudo] password for lorin:
# mkdir: created directory ‘/mnt/class8’
#
# alikot$ sudo sshfs lricker@class8: /mnt/class8
# The authenticity of host 'class8 (10.217.6.5)' can't be established.
# DSA key fingerprint is f1:4d:57:bc:e4:c7:ef:73:5e:1e:56:40:5b:c8:9d:d0.
# Are you sure you want to continue connecting (yes/no)? yes
# lricker@class8's password:
# alikot$ sudo chown lorin:rickernet -v /mnt/class8
# changed ownership of ‘/mnt/class8’ from root:root to lorin:rickernet
# alikot$ sshfs lricker@class8: /mnt/class8
# lricker@class8's password:

# echo "%bash-DCL-magik-I-SSHFS, mounting SSHFS connection to VMS class8,"
# echo "                         VMS password required --"
# sshfs lricker@class8.parsec.com: /mnt/class8  # -o reconnect -C -o workaround=all

# If "fuse: bad mount point `/mnt/class8': Transport endpoint is not connected"
#   occurs, do this (might need sudo):
#   $ fusermount -uz /mnt/class8   ...or...   $ umount -l /mnt/class8
# and then remount with sshfs

RG='set -f ; ResetGlobbing'

# A demonstration of bash globbing-suppression with $rby/argvdemo.rb:
alias noglobdemo="$RG $HOME/bin/argvdemo"

# This is a prototype DCL commands that requires bash globbing-suppression;
# ultimately re-done in $rby/dcl.rb as "rename" command -- see below:
alias  dclrename="$RG $HOME/bin/dclrename"

# DCL commands that require bash globbing-suppression --
# see $rby/dcl.rb and $rby/lib/DCLcommand.rb:
alias       copy="$RG $HOME/bin/dcllinks/copy"
alias     create="$RG $HOME/bin/dcllinks/create"
alias     delete="$RG $HOME/bin/dcllinks/delete"
alias        del="$RG $HOME/bin/dcllinks/delete"
alias  directory="$RG $HOME/bin/dcllinks/directory"
alias      purge="$RG $HOME/bin/dcllinks/purge"
alias     rename="$RG $HOME/bin/dcllinks/rename"
alias     search="$RG $HOME/bin/dcllinks/search"
alias       show="$RG $HOME/bin/dcllinks/show"

alias        dir="$RG $HOME/bin/dir"

# =========================

# show all the DCL commands:
alias dclshow="alias | grep ResetGlobbing"

# =========================

return 0  # don't: exit 0
