#!/usr/bin/env bash

# $HOME/bin/login/functions-ResetGlobbing
# Lorin Ricker: bash functions -- reset-globbing function for DCL Emulator

shF="$( basename ${0#-} ) - functions-ResetGlobbing"
Ident="${shF}  # (LMR version 1.01 of 05/01/2018)"
[ "$DEBUGMODE" \> "0" ] && echo "%login-I, ${Ident}"

# =========================
# Helper function to re-enable bash/shell globbing,
# used with alias commands of this form:
#
#  $ alias noglobdemo="set -f ; ResetGlobbing $HOME/bin/argvdemo"
#  $ alias rename="set -f ; ResetGlobbing $HOME/bin/rename"
#
ResetGlobbing()
  { CMD="$1"
    shift
    $CMD "$@"
    set +f
  }
export -f ResetGlobbing
# =========================
