#!/usr/bin/env bash

# $HOME/bin/login/git-magik
# Lorin Ricker: bash path functions

shF="$( basename ${0#-} ) - git-magik"
Ident="${shF}  # (LMR version 1.07 of 05/01/2018)"
[ "$DEBUGMODE" \> "0" ] && echo "%login-I, ${Ident}"

# use: $ gitshow
#
# Returns a report of local git ~/.gitconfig, including
#   git remote -v show, git fetch origin and git status
gitshow()
  {
    BOLD="\033[1m"
    NORM="\033[0m"
    # lsfunction -f git%
    # echo -e "\n\$ ${BOLD}git config --list${NORM}"
    # git config --list
    echo -e "\n\$ ${BOLD}cat ~/bin/gitconfig${NORM}  # (~/.gitconfig -> ~/bin/gitconfig)"
    /bin/cat ~/.gitconfig
    echo -e "\n\$ ${BOLD}git remote -v show${NORM}"
    git remote -v show
  }
export -f gitshow

# use: $ gitstat
#
# Returns a report of local git ~/.gitconfig, including
#   git remote -v show, git fetch origin and git status
gitstat()
  {
    BOLD="\033[1m"
    NORM="\033[0m"
    echo -e "\n\$ ${BOLD}git fetch origin${NORM}"
    git fetch origin
    echo -e "\n\$ ${BOLD}git status${NORM}"
    git status
  }
export -f gitstat

# use: $ gitconf
#
# Returns a report of local git ~/.gitconfig, including
#   git remote -v show, git fetch origin and git status
gitconf()
  {
    gitshow
    gitstat
  }
export -f gitconf

alias gitk="/usr/bin/gitk &"
