#!/usr/bin/env bash

# $HOME/bin/login/git-magik
# Lorin Ricker: bash path functions

shF=$( basename $0 )
Ident="${shF}  # (LMR version 1.01 of 02/10/2015)"
[ "$DEBUGMODE" = "1" ] && echo "%login-I, ${Ident}"

# use: $ gitremo
#
# Returns a quick-but-full report of current project's remote GitHub repository
gitremo()
  {
    git remote -v show
  }
export -f gitremo

# use: $ gitconf
#
# Returns a report of local git ~/.gitconfig, including gitremo
gitconf()
  {
    BOLD="\033[1m"
    NORM="\033[0m"
    lsfunction -f git%
    echo -e "\n\$ ${BOLD}git config --list${NORM}"
    git config --list
    echo -e "\n\$ ${BOLD}cat ~/bin/gitconfig${NORM}  # (~/.gitconfig -> ~/bin/gitconfig)"
    /bin/cat ~/.gitconfig
    echo -e "\n\$ ${BOLD}git remote -v show${NORM}"
    gitremo
    echo -e "\n\$ ${BOLD}git status${NORM}"
    git status
  }
export -f gitconf
